OPENAI_API_KEY = "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"
TAVUS_API_KEY = "f79b23d9334b462f81341c010e8f6f59"
